#!/bin/sh

prefix="/opt"
PATH=${prefix}/bin:${prefix}/sbin:/sbin:/bin:/usr/sbin:/usr/bin
OPID=/opt/var/run/sshd.pid

start() {
	echo "starting sshd..."
        # fix permissions issues
        chmod go-w $HOME
	/opt/sbin/sshd
	}

stop() {
	echo "stopping sshd..."
	kill `cat $OPID`
	}

status() {
	if [ -f $OPID ]; then
		echo "PID of sshd is `cat $OPID`"
	else
		echo "sshd is not running"
	fi
	}

restart() {
	kill -HUP $(cat $OPID)
        }

case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart)
                restart
	        ;;
        status) status
                ;;
        *)
                echo "Usage: $0 (start|stop|restart|status)"
                exit 1
                ;;
esac

exit 0
