#!/bin/sh

prefix="/opt"
PATH=${prefix}/bin:${prefix}/sbin:/sbin:/bin:/usr/sbin:/usr/bin
OPID=/opt/var/run/sshd.pid
KEY_DIR="/opt/etc/ssh"
COMMENT="$USER@$(hostname -f)"

check_gen_key () {
    local keylength=$2
    local keytype=$1
    [ -f $KEY_DIR/ssh_host_${keytype}_key ] || ssh-keygen -q -b $keylength -C "$COMMENT" -f $KEY_DIR/ssh_host_${keytype}_key -t ${keytype} -N ''
}

start() {
	echo "starting sshd..."
        # fix permissions issues
        chmod go-w $(getent passwd $USER | awk -F ':' '{print $6}')
	# create required keys if not exists
        check_gen_key rsa 4096
        check_gen_key dsa 1024
        check_gen_key ecdsa 521
        check_gen_key ed25519 4096
	
	/opt/sbin/sshd
	}

stop() {
	echo "stopping sshd..."
	kill `cat $OPID`
	}

status() {
	if [ -f $OPID ]; then
		echo "PID of sshd is `cat $OPID`"
	else
		echo "sshd is not running"
	fi
	}

restart() {
	kill -HUP $(cat $OPID)
        }

case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart)
                restart
	        ;;
        status) status
                ;;
        *)
                echo "Usage: $0 (start|stop|restart|status)"
                exit 1
                ;;
esac

exit 0
